print("This is a game of mad libs")
print("Would you like an action mad libs or a drama mad libs: Type either action or drama")
answer = raw_input()

if answer == "drama":
    print("Great you chose drama")
    print("Type in an adjective")
    x = raw_input()
    print("Type in a name")
    y = raw_input()
    print("Type in a number")
    z = raw_input()
    print("Type in the same name")
    a = raw_input()
    print("Type in a relative")
    b = raw_input()
    print("Type in the same name")
    c = raw_input()
    print("type in a place")
    d = raw_input()
    print("type in place")
    e = raw_input()
    print("Type in a verb ending in -ing")
    f = raw_input()
    print("Type in a plural noun")
    g = raw_input()
    print("Type in an adjective")
    h = raw_input()
    print("Type in an adjective")
    i = raw_input()
    print("Type in a person")
    j = raw_input()
    print("Type in an adjective -ly")
    k = raw_input()
    print("Here is your mad lib")
    print("A new and " + x + " fairy princess movie is coming out soon!")
    print("It will be about Snow " + y + " and the " + z + " dwarfs. ")
    print("Snow " + a + " is a princess whose beauty threatens her " + b + " , the queen ")
    print("Snow " + c + " is forced to flee from " + d + " and hides in nearby " + e)
    print("There, she discovers the dwarfs " + f + " in their " + g)
    print("But the queen finds her and casts a " + h + " spell on her")
    print("The dwarfs take care of her until the " + i + " " + j)
    print("comes to rescue her, and they all live " + k + " ever after!")
